<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-FFOHRV9Q2T4" name="Test" tests="4" failures="2" timestamp="14 Dec 2015 15:55:20 GMT" time="332.191" errors="0">
  <testcase name="starbucks" time="48.418" classname="testng.starbucksTest"/>
  <testcase name="starbucks" time="46.461" classname="testng.starbucksTest"/>
  <testcase name="starbucks" time="137.283" classname="testng.starbucksTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFailWithMessage(BasicTest.java:321)
	at testng.starbucksTest.starbucks(starbucksTest.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- starbucks -->
  <testcase name="starbucks" time="143.533" classname="testng.starbucksTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.perfectomobile.test.BasicTest.reportFailWithMessage(BasicTest.java:321)
	at testng.starbucksTest.starbucks(starbucksTest.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- starbucks -->
</testsuite> <!-- Test -->
