<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AdminITs-MacBook-Pro-2.local" name="testng.FindPost" tests="20" failures="0" timestamp="5 Nov 2015 15:41:58 GMT" time="494.847" errors="1">
  <testcase name="findPost" time="31.741" classname="testng.FindPost"/>
  <testcase name="findPost" time="41.288" classname="testng.FindPost"/>
  <testcase name="findPost" time="22.121" classname="testng.FindPost"/>
  <testcase name="findPost" time="22.394" classname="testng.FindPost"/>
  <testcase name="findPost" time="7.289" classname="testng.FindPost"/>
  <testcase name="findPost" time="35.672" classname="testng.FindPost"/>
  <testcase name="findPost" time="18.703" classname="testng.FindPost"/>
  <testcase name="findPost" time="11.558" classname="testng.FindPost"/>
  <testcase name="findPost" time="22.300" classname="testng.FindPost"/>
  <testcase name="findPost" time="19.586" classname="testng.FindPost"/>
  <testcase name="findPost" time="31.898" classname="testng.FindPost">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.perfectomobile.test.BasicTest.reportFail(BasicTest.java:297)
	at testng.FindPost.findPost(FindPost.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- findPost -->
  <testcase name="findPost" time="52.518" classname="testng.FindPost"/>
  <testcase name="findPost" time="7.274" classname="testng.FindPost"/>
  <testcase name="findPost" time="21.696" classname="testng.FindPost"/>
  <testcase name="findPost" time="11.787" classname="testng.FindPost"/>
  <testcase name="findPost" time="9.500" classname="testng.FindPost"/>
  <testcase name="findPost" time="14.770" classname="testng.FindPost"/>
  <testcase name="findPost" time="13.012" classname="testng.FindPost"/>
  <testcase name="findPost" time="60.532" classname="testng.FindPost"/>
  <testcase name="findPost" time="39.208" classname="testng.FindPost"/>
</testsuite> <!-- testng.FindPost -->
